# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1
  - nightly
os:
  - linux
  - osx
#arch:
#  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1
      os: linux
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: doctest
          using StatisticalTests
          doctest(StatisticalTests)
          include("docs/make.jl")'
      after_success: skip
