name = "StatisticalTests"
uuid = "bd11bef3-1250-4711-a621-198b27ede96b"
authors = ["Kiwamu Ishikura <ishikura.kiwamu@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
RDatasets = "0.5, 0.6"
julia = "1"

[extras]
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "RDatasets"]
