name = "StatisticalTests"
uuid = "bd11bef3-1250-4711-a621-198b27ede96b"
authors = ["Kiwamu Ishikura <ishikura.kiwamu@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"

[targets]
test = ["Test", "CategoricalArrays", "DataFrames", "RDatasets"]
